[package]
name = "noctfs"
version = "0.1.1"
edition = "2021"
build = "build.rs"

[features]
default = ["std"]
std = []

[dependencies]
bitflags = "2.9.0"
no_std_io = { version = "0.6.0", features = ["alloc"] }
