[package]
name = "noctfs"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[features]
default = ["std"]
std = []

[dependencies]
arrayref = "0.3.9"
bitflags = "2.9.0"
no_std_io = { version = "0.6.0", features = ["alloc"] }
